name: bloc_knowledge_sharing
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: any
  http: ^0.12.0
  equatable: ^1.1.0
  fluttertoast: ^3.1.3
  provider: ^4.0.4
  retrofit: ^1.3.1+1
  connectivity: ^0.4.8+1
  json_annotation: ^3.0.1
  dynamic_theme: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^1.2.2+1
  build_runner: ^1.7.4
  json_serializable: ^3.2.0
  

flutter:
  uses-material-design: true
